'use strict';
// Run only with demo emulators. This test refuses live databases and credentials.
const test=require('node:test'),assert=require('node:assert/strict');
if(!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_AUTH_EMULATOR_HOST||!process.env.GCLOUD_PROJECT?.startsWith('demo-'))throw new Error('Emulators with demo project required');
const functionRequire=require('node:module').createRequire(require('node:path').resolve(__dirname,'../functions/package.json'));
const {initializeApp}=functionRequire('firebase-admin/app');
const {getFirestore}=functionRequire('firebase-admin/firestore');
const {getAuth}=functionRequire('firebase-admin/auth');
initializeApp({projectId:process.env.GCLOUD_PROJECT});const db=getFirestore(),auth=getAuth(),prefix='ceLitePreview';
const members=db.collection(prefix+'Members'),control=db.collection(prefix+'Control').doc('settings');
const endpoint=`http://127.0.0.1:5001/${process.env.GCLOUD_PROJECT}/asia-southeast1/ceLiteApi`;
async function login(uid){await auth.createUser({uid,email:uid+'@example.test',password:'EmulatorOnly!1234'});const response=await fetch('http://'+process.env.FIREBASE_AUTH_EMULATOR_HOST+'/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=fake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:uid+'@example.test',password:'EmulatorOnly!1234',returnSecureToken:true})});return (await response.json()).idToken;}
async function call(token,data){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({data})});return await response.json();}
const op=()=>require('node:crypto').randomUUID();
test('end-to-end server authorization, concurrent rewards, idempotency, month close, isolation',async()=>{
 const [adminToken,aToken,bToken]=await Promise.all(['admin','a','b'].map(login));
 await control.set({startMonth:'2026-09',revision:0,announcement:{active:false},rewardBudget:{}});
 for(const id of ['admin','a','b'])await members.doc(id).set({name:id,username:id,role:id==='admin'?'admin':'employee',active:true,points:100,streak:5,mustChangePassword:false,photo:null});
 await db.collection(prefix+'Rewards').doc('cash').set({name:'cash',description:'test',cost:100,value:1000,type:'cash',stock:1,year:2026,active:true,photo:null});
 assert.equal((await call(null,{action:'state'})).error.status,'UNAUTHENTICATED');
 assert.equal((await call(aToken,{action:'budget',budget:1000,operationId:op()})).error.status,'PERMISSION_DENIED');
 const employeeState=(await call(aToken,{action:'state'})).result;
 assert.deepEqual(employeeState.employees.map(e=>e.id),['a']);assert.equal(employeeState.teamRank.total,2);
 const photo='data:image/jpeg;base64,/9j/2Q==';
 assert.ok((await call(aToken,{action:'profile',id:'b',photo,operationId:op()})).result);
 assert.equal((await members.doc('a').get()).data().photo,photo);assert.equal((await members.doc('b').get()).data().photo,null,'profile action always edits the caller');
 assert.equal((await call(aToken,{action:'profile',photo:'javascript:alert(1)',operationId:op()})).error.status,'FAILED_PRECONDITION');
 assert.ok((await call(aToken,{action:'profile',photo:null,operationId:op()})).result);
 assert.equal((await call(aToken,{action:'announcement',title:'test',body:'test',active:true,operationId:op()})).error.status,'PERMISSION_DENIED');
 assert.ok((await call(adminToken,{action:'announcement',title:'team notice',body:'test only',active:true,operationId:op()})).result);
 assert.equal((await call(aToken,{action:'state'})).result.announcement.title,'team notice');
 const coffee=db.collection(prefix+'Rewards').doc('coffee');
 await coffee.set({name:'coffee',description:'test',cost:3,value:50,type:'coffee',active:true,photo:null});
 assert.equal((await call(aToken,{action:'archiveReward',id:'coffee',operationId:op()})).error.status,'PERMISSION_DENIED');
 assert.ok((await call(adminToken,{action:'archiveReward',id:'coffee',operationId:op()})).result);
 assert.equal((await coffee.get()).data().archived,true);
 assert.equal((await call(aToken,{action:'state'})).result.rewards.some(r=>r.id==='coffee'),false);
 assert.equal((await call(aToken,{action:'redeem',rewardId:'coffee',operationId:op()})).error.status,'FAILED_PRECONDITION');
 assert.ok((await call(adminToken,{action:'restoreReward',id:'coffee',operationId:op()})).result);
 assert.equal((await call(aToken,{action:'state'})).result.rewards.some(r=>r.id==='coffee'),true);
 await coffee.update({active:false});
 assert.ok((await call(adminToken,{action:'archiveReward',id:'coffee',operationId:op()})).result);
 assert.ok((await call(adminToken,{action:'restoreReward',id:'coffee',operationId:op()})).result);
 assert.equal((await coffee.get()).data().active,false,'restoring an inactive reward must not open it for redemption');
 const [r1,r2]=await Promise.all([aToken,bToken].map(token=>call(token,{action:'redeem',rewardId:'cash',operationId:op()})));
 assert.equal([r1,r2].filter(r=>r.result).length,1,'single cash slot must survive simultaneous requests');
 const request=(await db.collection(prefix+'Requests').get()).docs[0],winner=request.data().employeeId;
 assert.equal(request.data().employeeName,winner,'request snapshots the submitter name for LINE notifications');
 const approval={action:'decide',id:request.id,status:'approved',operationId:op()};
 assert.ok((await call(adminToken,approval)).result);assert.ok((await call(adminToken,approval)).result);
 assert.equal((await members.doc(winner).get()).data().points,0,'retries must not deduct twice');
 assert.equal((await call(adminToken,{...approval,operationId:op()})).error.status,'FAILED_PRECONDITION');
 const delivery={action:'deliver',id:request.id,paidAmount:950,operationId:op()};assert.ok((await call(adminToken,delivery)).result);assert.ok((await call(adminToken,delivery)).result);
 assert.equal((await members.doc(winner).get()).data().points,0);
 const expectedRevision=(await control.get()).data().revision;
 const close={action:'closeMonth',month:'2026-09',checks:{a:{cases:10,kpi:true,extra:3},b:{cases:0,kpi:true}},teamTop:true,expectedRevision,operationId:op()};
 assert.ok((await call(adminToken,close)).result);assert.ok((await call(adminToken,close)).result);
 const closed=(await db.collection(prefix+'Months').doc('2026-09').get()).data();assert.equal(closed.entries.find(e=>e.employeeId==='a').streakAfter,0);assert.equal(closed.entries.find(e=>e.employeeId==='a').kpiBonus,0);assert.equal(closed.entries.find(e=>e.employeeId==='a').extraBonus,3);
 assert.equal((await call(adminToken,{...close,operationId:op(),expectedRevision:(await control.get()).data().revision})).error.status,'FAILED_PRECONDITION');
 await Promise.all(['a','b'].map(id=>members.doc(id).update({points:10})));
 assert.ok((await call(adminToken,{action:'reward',reward:{name:'WFH',description:'one day',cost:1,value:null,type:'coffee',stock:1,special:true,active:true,photo:null},operationId:op()})).result);
 const wfhDoc=(await db.collection(prefix+'Rewards').where('name','==','WFH').get()).docs[0];
 assert.equal(wfhDoc.data().special,true);assert.equal(wfhDoc.data().value,null);
 const [wa,wb]=await Promise.all([aToken,bToken].map(token=>call(token,{action:'redeem',rewardId:wfhDoc.id,operationId:op()})));
 assert.ok(wa.result&&wb.result,'both requests may wait for the single right');
 const wfhRequests=(await db.collection(prefix+'Requests').where('rewardId','==',wfhDoc.id).get()).docs;
 assert.equal(wfhRequests.length,2);
 assert.ok((await call(adminToken,{action:'decide',id:wfhRequests[0].id,status:'approved',operationId:op()})).result);
 assert.equal((await call(adminToken,{action:'decide',id:wfhRequests[1].id,status:'approved',operationId:op()})).error.status,'FAILED_PRECONDITION');
 assert.ok((await call(adminToken,{action:'decide',id:wfhRequests[1].id,status:'rejected',operationId:op()})).result);
 const wfhState=(await call(adminToken,{action:'state'})).result.rewards.find(r=>r.id===wfhDoc.id);
 assert.equal(wfhState.remaining,0);

 await members.doc('a').update({mustChangePassword:true});
 assert.equal((await call(aToken,{action:'state'})).result.mustChangePassword,true);
 assert.equal((await call(aToken,{action:'redeem',rewardId:'cash',operationId:op()})).error.status,'FAILED_PRECONDITION');
 await members.doc('b').update({active:false});assert.equal((await call(bToken,{action:'state'})).error.status,'PERMISSION_DENIED');
 const direct=await fetch('http://'+process.env.FIRESTORE_EMULATOR_HOST+'/v1/projects/'+process.env.GCLOUD_PROJECT+'/databases/(default)/documents/'+prefix+'Members/a',{headers:{Authorization:'Bearer '+aToken}});
 assert.equal(direct.status,403,'direct clients must not read private member documents');
 const tamper=await fetch('http://'+process.env.FIRESTORE_EMULATOR_HOST+'/v1/projects/'+process.env.GCLOUD_PROJECT+'/databases/(default)/documents/'+prefix+'Members/a',{method:'PATCH',headers:{Authorization:'Bearer '+aToken,'Content-Type':'application/json'},body:JSON.stringify({fields:{role:{stringValue:'admin'},points:{integerValue:'999'}}})});assert.equal(tamper.status,403);
});
